---
title: "Rworksheet_Basultin4a"
author: "Jonadrew Darren Basultin"
date: "2023-11-08"
output: pdf_document
---

#1
#A
```{r NUM1A}
ShoeSize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5)
Height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0)

df <- data.frame(ShoeSize, Height)
print(df)
```
#B
```{r NUM1B}
males <- subset(df, ShoeSize>=9)
females <- subset(df, ShoeSize<9)

print(males)
print(females)
```
#C
```{r NUM1C}
mean_ShoeSize <- mean(ShoeSize)
cat("Mean ShoeSize:", mean_ShoeSize, "\n")
mean_Height <- mean(Height)
cat("Mean Height:", mean_Height, "\n")
```
#D
# For instance,Taller people often have bigger feet and therefore tend to wear larger shoe sizes. #However, this isn't a fixed rule, as factors like genetics and individual foot structure can #influence the relationship between height and shoe size.


#2
```{r NUM2}
months <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December","August","August","September","November","February", "April")

factor_months_vector <- factor(months)
print(factor_months_vector)
```
#3
```{r NUM3}
summary(months)
summary(factor_months_vector)
#While months will give you a count of each occurrence of each month, factor_months_vector is more helpful in this situation for summing up the various months that are included in the data.
```
#4
```{r NUM4}
direction <- c("East", "West", "North")
frequency <- c(1, 4, 3)

factor_data <- factor(direction, levels = c("East", "West", "North"))

levels(factor_data) <- frequency

new_order_data <- factor_data
print(new_order_data)

```
#5
```{r NUM5}
student_table <- read.table(file = 'import_march.csv', header = TRUE, sep = ',')
student_table

```
#6
```{r NUM6}

random_number <- sample(1:50, 1)

cat("The chosen number is:", random_number, "\n")

if (random_number == 20) {
  cat("TRUE\n")
} else if (random_number < 1 || random_number > 50) {
  cat("The number selected is beyond the range of 1 to 50\n")
} else {
  cat(random_number, "\n")
}

```
#7
```{r NUM7}

calculate_minimum_bills <- function(price) {
  bill_denominations <- c(50, 100, 200, 500, 1000)
  num_bills <- 0
  
  for (bill in rev(bill_denominations)) {
    while (price >= bill) {
      price <- price - bill
      num_bills <- num_bills + 1
    }
  }
  
  cat("Minimum number of bills needed: ", num_bills, "\n")
}

price_of_snack <- 500
if (price_of_snack %% 50 == 0) {
  calculate_minimum_bills(price_of_snack)
} else {
  cat("Price of snack is not divisible by 50 pesos.\n")
}

```
#8

#A
```{r NUM8A}
data <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)

print(data)
```
#B
```{`r NUM8B}
for (i in 1:nrow(data)) {
  name <- data$Name[i]
  average_score <- (data$Grade1[i] + data$Grade2[i] + data$Grade3[i] + data$Grade4[i]) / 4
  
  if (average_score > 90) {
    cat(name, "'s average grade this semester is", round(average_score, 2), "\n")
  }
}
```
#c
```{r NUM8C}
for (i in 1:4) {
  test_scores <- data[, i + 1]
  test_average <- sum(test_scores) / nrow(data)
  
  if (test_average < 80) {
    cat("The", i, "test was difficult.\n")
  }
}
```
#D
```{r NUM8D}
for (i in 1:nrow(data)) {
  name <- data$Name[i]
  max_score <- max(data[i, -1])
  
  if (max_score > 90) {
    cat(name, "'s highest grade this semester is", max_score, "\n")
  }
}
```